### ISSUE TITLE
MAP UI の開発

### ISSUE THREAD

**Issue by s14t284** [s14t284/virtual-pilgrimage#15]
仮想的に 88 箇所巡りをしている程で、MAP 上に以下の情報を表示する UI を開発する
- 自身の仮想的な現在地
- 次のお寺までの距離
- 既に到着しているお寺の境内の写真・情報の表示
- 他にもあれば追記

まずは Google MAP API などの MAP の UI のうち、どれを使うか検討し、簡単に MAP を表示するところから始めていく

**Comment by s14t284** [comment]
タスク内でやることが広すぎるので、分割しても良い
もしくは PR は分割しながら開発する

**Comment by itomizu** [comment]
> - 自身の仮想的な現在地

ユーザのアイコン周りの追加 #27 で対応

**Comment by s14t284** [comment]
ref. https://github.com/s14t284/virtual-pilgrimage/pull/36
