### ISSUE TITLE
DirectionAPIのキャッシュ導入

### ISSUE THREAD

**Issue by itomizu** [s14t284/virtual-pilgrimage#43]
経路計算にDirectionAPIを使用している。
1回のリクエストあたり約0.5円（1$=¥108）と比較的高い

複数回実行された場合にも料金がかからない方法を検討する（例：キャッシュなど）

**Comment by s14t284** [comment]
Direction API はA地点からB地点までの経路を返却する。
本アプリにおいて、経路は 87 パターン程度に限られる。

よって、Direction API にリクエストするようなスクリプトを実装し、取得できた結果をローカルのファイルなどに吐き出して、Firestore に保存しておくほうが以下の観点から良さそう
- 運用コスト（1call 0.5円は高め）
- 描画速度（Firestore に問い合わせるほうが高速）
